# Generated by Django 5.0.4 on 2024-04-28 23:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('document', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
