# Generated by Django 5.0.4 on 2024-04-29 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('document', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='document',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
    ]
