# Generated by Django 5.0.4 on 2024-05-08 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0003_analista_rename_document_usuario_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_registrado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Analista',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
