# Generated by Django 5.0.4 on 2024-05-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
