# Generated by Django 5.0.4 on 2024-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_registrado',
            name='idrol',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario_registrado',
            name='rol',
            field=models.TextField(default='Usuario', max_length=100),
        ),
    ]
