# Generated by Django 5.0.4 on 2024-05-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_usuario_registrado_idrol_usuario_registrado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTERNET_MOVIL_CARGO_FIJO_INGRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.IntegerField()),
                ('TRIMESTRE', models.IntegerField()),
                ('MES_DEL_TRIMESTRE', models.IntegerField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('EMPRESA', models.CharField(max_length=100)),
                ('ID_SEGMENTO', models.IntegerField()),
                ('SEGMENTO', models.TextField(default='Personas', max_length=100)),
                ('ID_TERMINAL', models.IntegerField()),
                ('TERMINAL', models.TextField(default='Teléfono móvil', max_length=100)),
                ('INGRESOS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='INTERNET_MOVIL_CARGO_FIJO_TRAFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.IntegerField()),
                ('TRIMESTRE', models.IntegerField()),
                ('MES_DEL_TRIMESTRE', models.IntegerField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('EMPRESA', models.CharField(max_length=100)),
                ('TRAFICO', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='INTERNET_MOVIL_DEMANDA_ABONADOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.IntegerField()),
                ('TRIMESTRE', models.IntegerField()),
                ('MES_DEL_TRIMESTRE', models.IntegerField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('EMPRESA', models.CharField(max_length=100)),
                ('ID_MODALIDAD_PAGO', models.IntegerField()),
                ('MODALIDAD_PAGO', models.CharField(max_length=100)),
                ('ID_TERMINAL', models.IntegerField()),
                ('TERMINAL', models.CharField(max_length=100)),
                ('ID_TECNOLOGIA', models.IntegerField()),
                ('TECNOLOGIA', models.CharField(max_length=100)),
                ('CANTIDAD_ABONADOS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='INTERNET_MOVIL_DEMANDA_TRAFICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.IntegerField()),
                ('TRIMESTRE', models.IntegerField()),
                ('MES_DEL_TRIMESTRE', models.IntegerField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('EMPRESA', models.CharField(max_length=100)),
                ('ID_MODALIDAD_PAGO', models.IntegerField()),
                ('TRAFICO', models.IntegerField()),
                ('MODALIDAD_PAGO', models.CharField(max_length=100)),
            ],
        ),
    ]
