# Generated by Django 5.0.4 on 2024-05-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_internet_movil_cargo_fijo_ingre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTERNET_MOVIL_CARGO_FIJO_SUSCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.IntegerField()),
                ('TRIMESTRE', models.IntegerField()),
                ('MES_DEL_TRIMESTRE', models.IntegerField()),
                ('ID_SEGMENTO', models.IntegerField()),
                ('SEGMENTO', models.TextField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('EMPRESA', models.TextField()),
                ('ID_TERMINAL', models.IntegerField()),
                ('TERMINAL', models.TextField()),
                ('ID_TECNOLOGIA', models.IntegerField()),
                ('TECNOLOGIA', models.TextField()),
                ('CANTIDAD_SUSCRIPTORES', models.IntegerField()),
            ],
        ),
    ]
