# Generated by Django 5.0.4 on 2024-05-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_internet_movil_cargo_fijo_ingre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet_movil_cargo_fijo_ingre',
            name='INGRESOS',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='internet_movil_cargo_fijo_suscr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internet_movil_cargo_fijo_trafi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_abonados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_ingresos',
            name='INGRESOS',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_ingresos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_trafico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
