# Generated by Django 5.0.4 on 2024-05-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_internet_movil_cargo_fijo_ingre_ingresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet_movil_cargo_fijo_trafi',
            name='TRAFICO',
            field=models.BigIntegerField(),
        ),
    ]
