# Generated by Django 5.0.4 on 2024-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_internet_movil_cargo_fijo_trafi_trafico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet_movil_demanda_ingresos',
            name='ID_MODALIDAD_PAGO',
            field=models.TextField(),
        ),
    ]
