# Generated by Django 5.0.4 on 2024-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_internet_movil_demanda_trafico_trafico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internet_movil_cargo_fijo_suscr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internet_movil_cargo_fijo_trafi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_abonados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_ingresos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internet_movil_demanda_trafico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
